import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#000000] to-[#1c1d2d]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[15rem]">
            Anecdote <span className="text-[hsl(280,100%,70%)]">AI</span>
          </h1>
          <p className="text-[hsl(300,1%,77%)] text-lg mb-28">an ai worthy of passing the turning test</p>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Chat</h3>
              <div className="text-lg">
                Get actual advice from real anecodtes from the internet instead of robotic inhuman responses!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Web Crawler</h3>
              <div className="text-lg">
                This is the crawler that collected the anecodte data that the model is trained on.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
